package com.backend_project.hotel.service;

import com.backend_project.hotel.model.HotelModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfGenerationService {

    public byte[] generateStaffPdf(HotelModel staff) throws DocumentException {
        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Add Header
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BaseColor.BLUE);
            Paragraph header = new Paragraph("Revuzz Hotel", headerFont);
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);

            Font subHeaderFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
            Paragraph subHeader = new Paragraph("Kollam, Kerala, 691572, Thiruvananthapuram\nPhone: +91 9876543210 | Email: revuzz@hotel.com", subHeaderFont);
            subHeader.setAlignment(Element.ALIGN_CENTER);
            subHeader.setSpacingAfter(10);
            document.add(subHeader);

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.DARK_GRAY);
            Paragraph title = new Paragraph("Staff Profile: " + staff.getFullname(), titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Add Image if available
            if (staff.getImage() != null && !staff.getImage().isEmpty()) {
                try {
                    Image img = Image.getInstance("uploads/" + staff.getImage());
                    img.scaleToFit(100, 100);
                    img.setAlignment(Element.ALIGN_CENTER);
                    document.add(img);
                } catch (Exception e) {
                    Paragraph noImage = new Paragraph("No Image Available", subHeaderFont);
                    noImage.setAlignment(Element.ALIGN_CENTER);
                    document.add(noImage);
                }
            }

            // Create Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(80);
            table.setWidths(new float[]{1, 2});
            table.setSpacingBefore(20);

            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 10);
            Font cellHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);

            // Add Table Headers
            PdfPCell cell;
            cell = new PdfPCell(new Phrase("Field", cellHeaderFont));
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell.setPadding(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Details", cellHeaderFont));
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell.setPadding(5);
            table.addCell(cell);

            // Add Table Data
            addTableRow(table, "ID", String.valueOf(staff.getStaffId()), cellFont);
            addTableRow(table, "Username", staff.getUsername(), cellFont);
            addTableRow(table, "Full Name", staff.getFullname(), cellFont);
            addTableRow(table, "Email", staff.getEmail(), cellFont);
            addTableRow(table, "Date of Birth", staff.getDateOfBirth().toString(), cellFont);
            addTableRow(table, "Phone", staff.getPhonenumber(), cellFont);
            addTableRow(table, "Role", staff.getRole(), cellFont);
            addTableRow(table, "Joining Date", staff.getJoiningDate().toString(), cellFont);
            addTableRow(table, "Experience", staff.getExperience() + " years", cellFont);
            addTableRow(table, "Qualification", staff.getQualification(), cellFont);

            document.add(table);

            // Add Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.GRAY);
            Paragraph footer = new Paragraph("Generated by Revuzz Hotel Management System | Contact: revuzz@hotel.com", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            document.add(footer);

            document.close();
        } catch (Exception e) {
            throw new DocumentException("Error generating PDF: " + e.getMessage());
        }

        return out.toByteArray();
    }

    public byte[] generateAllStaffPdf(List<HotelModel> staffList) throws DocumentException {
        Document document = new Document(PageSize.A4.rotate());
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Add Header
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BaseColor.BLUE);
            Paragraph header = new Paragraph("Revuzz Hotel", headerFont);
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);

            Font subHeaderFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
            Paragraph subHeader = new Paragraph("Kollam, Kerala, 691572, Thiruvananthapuram\nPhone: +91 9876543210 | Email: revuzz@hotel.com", subHeaderFont);
            subHeader.setAlignment(Element.ALIGN_CENTER);
            subHeader.setSpacingAfter(10);
            document.add(subHeader);

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.DARK_GRAY);
            Paragraph title = new Paragraph("Staff Management Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(10);
            document.add(title);

            Paragraph totalStaff = new Paragraph("Total Staff Members: " + staffList.size(), subHeaderFont);
            totalStaff.setAlignment(Element.ALIGN_CENTER);
            totalStaff.setSpacingAfter(20);
            document.add(totalStaff);

            // Create Table
            PdfPTable table = new PdfPTable(11);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{0.5f, 0.8f, 1, 1.5f, 2, 1, 1, 1, 1, 0.8f, 1.5f});
            table.setSpacingBefore(20);

            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 8);
            Font cellHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8);

            // Add Table Headers
            String[] headers = {"ID", "Image", "Username", "Full Name", "Email", "DOB", "Phone", "Role", "Joining Date", "Experience", "Qualification"};
            for (String headerText : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(headerText, cellHeaderFont));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setPadding(5);
                table.addCell(cell);
            }

            // Add Table Data
            for (HotelModel staff : staffList) {
                table.addCell(new Phrase(String.valueOf(staff.getStaffId()), cellFont));
                
                PdfPCell imageCell = new PdfPCell();
                if (staff.getImage() != null && !staff.getImage().isEmpty()) {
                    try {
                        Image img = Image.getInstance("uploads/" + staff.getImage());
                        img.scaleToFit(20, 20);
                        imageCell.addElement(img);
                    } catch (Exception e) {
                        imageCell.addElement(new Phrase("No Image", cellFont));
                    }
                } else {
                    imageCell.addElement(new Phrase("No Image", cellFont));
                }
                table.addCell(imageCell);

                table.addCell(new Phrase(staff.getUsername(), cellFont));
                table.addCell(new Phrase(staff.getFullname(), cellFont));
                table.addCell(new Phrase(staff.getEmail(), cellFont));
                table.addCell(new Phrase(staff.getDateOfBirth().toString(), cellFont));
                table.addCell(new Phrase(staff.getPhonenumber(), cellFont));
                table.addCell(new Phrase(staff.getRole(), cellFont));
                table.addCell(new Phrase(staff.getJoiningDate().toString(), cellFont));
                table.addCell(new Phrase(staff.getExperience() + " years", cellFont));
                table.addCell(new Phrase(staff.getQualification(), cellFont));
            }

            document.add(table);

            // Add Role Summary
            Font summaryFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.DARK_GRAY);
            Paragraph summaryTitle = new Paragraph("Staff Summary", summaryFont);
            summaryTitle.setSpacingBefore(20);
            document.add(summaryTitle);

            Font summaryContentFont = FontFactory.getFont(FontFactory.HELVETICA, 8);
            for (String role : staffList.stream().map(HotelModel::getRole).distinct().toList()) {
                long count = staffList.stream().filter(s -> s.getRole().equals(role)).count();
                Paragraph summaryLine = new Paragraph(role + ": " + count + " members", summaryContentFont);
                summaryLine.setSpacingBefore(5);
                document.add(summaryLine);
            }

            // Add Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.GRAY);
            Paragraph footer = new Paragraph("Generated by Revuzz Hotel Management System | Contact: revuzz@hotel.com", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            document.add(footer);

            document.close();
        } catch (Exception e) {
            throw new DocumentException("Error generating PDF: " + e.getMessage());
        }

        return out.toByteArray();
    }

    private void addTableRow(PdfPTable table, String field, String value, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(field, font));
        cell.setPadding(5);
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(value, font));
        cell.setPadding(5);
        table.addCell(cell);
    }
}